########################################
# Handlers for restarting services
#

- name: reload apache
  action: service name=httpd state=reloaded

- name: restart crond
  action: service name=crond state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: reload httpd
  action: service name=httpd state=reloaded

- name: restart iptables
  action: service name=iptables state=restarted

- name: restart ip6tables
  action: service name=ip6tables state=restarted

- name: restart lighttpd
  action: service name=lighttpd state=restarted

- name: restart ntpd
  action: service name=ntpd state=restarted

- name: restart postfix
  action: service name=postfix state=restarted

- name: restart rsyslog
  action: service name=rsyslog state=restarted

- name: restart sshd
  action: service name=sshd state=restarted

- name: restart network
  action: service name=network state=restarted

- name: restart glusterd
  service: name=glusterd state=restarted

- name: restart supervisord
  service: name=supervisord state=restarted

- name: restart dhcpd
  service: name=dhcpd state=restarted

- name: restart memcached
  service: name=memcached state=restarted

- name: reload systemd
  command: systemctl daemon-reload

- name: restart bridge
  shell: /usr/lib/systemd/systemd-sysctl --prefix=/proc/sys/net/bridge

- name: hup libvirtd
  command: pkill -HUP libvirtd
  ignore_errors: true
  when: inventory_hostname.startswith('buildhw')

- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart varnish
  service: name=varnish state=restarted

- name: restart keepalived
  service: name=keepalived state=restarted

- name: restart mariadb
  service: name=mariadb state=restarted

- name: restart postgresql
  service: name=postgresql state=restarted

- name: restart squid
  service: name=squid state=restarted
