---
- name: install pkgs for copr-frontend
  action: yum state=present pkg={{ item }}
  with_items:
  - "copr-frontend"
  - "bash-completion"
  - "mod_ssl"
  - "postfix"
  tags:
  - packages

- name: enable and start redis
  service: name=redis enabled=yes state=started

# postfix config
- include: "postfix_setup.yml"

- name: enable and start postfix
  service: name=postfix enabled=yes state=started

- name: website translate
  include: "translate.yml"
  tags:
  - config

- name: install copr configs
  template: src="copr.conf" dest=/etc/copr/copr.conf owner=copr-fe group=copr-fe mode=600
  notify:
  - restart httpd
  tags:
  - config

- name: copy apache files to conf.d
  copy: src="httpd/{{ item }}" dest="/etc/httpd/conf.d/{{ item }}" owner=root group=root mode=0644
  with_items:
  - "welcome.conf"
  - "10_copr-fe.conf"
  - "10_copr-fe_ssl.conf"
  - "20_copr-be.conf"
  - "20_copr-be_ssl.conf"
  tags:
  - config
  notify:
  - restart httpd

- name: make copr dirs
  file: state=directory path={{ item }} owner=copr-fe group=copr-fe recurse=yes
  with_items:
  - /var/lib/copr/jobs
  - /var/lib/copr/data
  - /var/lib/copr/public_html/results
  - /var/log/copr

- name: Umask results
  command: /usr/bin/umask 0000 chdir=/var/lib/copr/public_html/results

- name: make http log dirs
  file: state=directory path={{ item }}
  with_items:
  - /var/log/httpd

- name: install indexes files
  copy: src="static/{{ item }}" dest="/var/lib/copr/public_html/{{ item }}" owner=copr-fe group=copr-fe mode=0644
  with_items:
  - footer.html
  - header.html
  - style.css
  - favicon.ico
  - bg.png
  - bottom.png
  - robots.txt
  notify:
  - restart httpd

- name: install ssl certificates for production
  include: "install_certs.yml"
#  when: not devel
  tags:
  - config

# postgresql config
- include: "psql_setup.yml"

- name: enable services
  service: state=running enabled=yes name={{ item }}
  with_items:
  - httpd
  - postgresql

- name: See link file
  stat: path=/usr/local/bin/copr-manage
  register: manage_installed

- name: link copr-frontend manage tool
  shell: ln -s /usr/share/copr/coprs_frontend/manage.py /usr/local/bin/copr-manage
  when: not manage_installed.stat.exists

- name: create the db schema
  shell: cd /usr/share/copr/coprs_frontend; copr-manage create_db --alembic alembic.ini

- name: creates a mock chroot in db
#  su: true
#  su_user: copr-fe
  shell: copr-manage create_chroot fedora-rawhide-x86_64 fedora-rawhide-i386 fedora-22-x86_64 fedora-22-i386 fedora-21-x86_64 fedora-21-i386 fedora-20-x86_64 fedora-20-i386 epel-7-x86_64 epel-6-x86_64 epel-6-i386 epel-5-x86_64 epel-5-i386
# runserver: copr-manage runserver --host <FQDN> --port XX --debug

#- name: set acl for logstash to access httpd logs
#  acl: name=/var/log/httpd entity=logstash etype=user permissions=rx state=present
